// Generated by https://quicktype.io

export interface CostosEmpleadoResponse {
  data:          CostoEmpleado[];
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface CostoEmpleado {
  idCosto:                        number;
  numEmpleadoRrHh:                string;
  nuAnno:                         number;
  nuMes:                          number;
  numEmpleadoNoi:                 number;
  idpersona:                      number;
  nombrePersona:                  number;
  reubicacion:                    string;
  idpuesto:                       number;
  puesto:                         string;
  numProyecto:                    number;
  proyecto:                       string;
  idUnidadNegocio:                number;
  unidadNegocio:                  string;
  idEmpresa:                      number;
  Empresa:                        string;
  timesheet:                      string;
  idEmpleadoJefe:                 string;
  nombreJefe:                     string;
  fechaIngreso:                   string;
  antiguedad:                     number;
  avgDescuentoEmpleado:           number;
  montoDescuentoMensual:          number;
  sueldoNetoPercibidoMensual:     number;
  retencionImss:                  number;
  ispt:                           number;
  sueldoBrutoInflacion:           number;
  anual:                          number;
  aguinaldoCantMeses:             number;
  aguinaldoMontoProvisionMensual: number;
  pvDiasVacasAnuales:             number;
  pvProvisionMensual:             number;
  indemProvisionMensual:          number;
  avgBonoAnualEstimado:           number;
  bonoAnualProvisionMensual:      number;
  sgmmCostoTotalAnual:            number;
  sgmmCostoMensual:               number;
  svCostoTotalAnual:              number;
  svCostoMensual:                 number;
  vaidCostoMensual:               number;
  vaidComisionCostoMensual:       number;
  ptuProvision:                   number;
  beneficios:                     null;
  impuesto3sNomina:               number;
  imss:                           number;
  retiro2:                        number;
  cesantesVejez:                  number;
  infonavit:                      number;
  cargasSociales:                 number;
  costoMensualEmpleado:           number;
  costoMensualProyecto:           number;
  costoAnualEmpleado:             number;
  indiceCostoLaboral:             number;
  indiceCargaLaboral:             number;
  fechaActualizacion:             string;
  regHistorico:                   boolean;
  ciudad:                         string;
  costoSalarioBruto:              number;
  costoSalarioNeto:               number;
  empresa:                        string;
  aguinaldoCantidadMeses:         number;
  nombreCompletoEmpleado:         string;
  
}

export const encabezados = Object.freeze([
  // {id: 'id', label: 'Id'},
  {id: 'numEmpleadoRrHh', label: 'Número de empleado RRHH'},
  {id: 'numEmpleadoNoi', label: 'Número de empleado NOI'},
  {id: 'nombreCompletoEmpleado', label: 'Nombre'},
  {id: 'ciudad', label: 'Ciudad base de trabajo'},
  {id: 'puesto', label: 'Puesto'},
  {id: 'numProyecto', label: 'Proyecto'},
  {id: 'sueldoBruto', label: 'Sueldo bruto (inflación %)'},
  {id: 'cargasSociales', label: 'Cargas Sociales'},
  {id: 'costoMensualEmpleado', label: 'Costo Mensual Empleado'},
  //{id: 'chunidad_negocio', label: 'Unidad de negocio'},
  //{id: 'dtfecha_ingreso', label: 'Fecha de ingreso'},
  //{id: 'dtfecha_salida', label: 'Fecha de salida'},
  //{id: 'dtfecha_ultimo_reingreso', label: 'Fecha de reingreso'},
  //{id: 'chnss', label: 'Nss'},
  //{id: 'chemail_bovis', label: 'Email Bovis'},
  //{id: 'nuantiguedad', label: 'Antiguedad'},
  //{id: 'nufondo_fijo', label: 'Fondo fijo'}
])

