// Generated by https://quicktype.io

export interface ObtenerClientesResponse {
    data:          Puesto[];
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface Puesto {
    nukid_puesto: number;
    nukidnivel: number;
    chpuesto:       string;
    nusalario_min:   string;
    nusalario_max:   string;
    nusalario_prom:   string;
    boactivo:    boolean;
}
