// Generated by https://quicktype.io

export interface ObtenerUsuarioTimesheetResponse {
    data:          UsuarioTimesheet[];
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface UsuarioTimesheet {
    id:              number;
    usuario:         string;
    numEmpleadoRrHh: string;
    nombreEmpleado:  string;
    numProyecto:     number;
	nombreProyecto:  string;
}
