// Generated by https://quicktype.io

export type EstadosList = 'todos' | 'activos' | 'inactivos'

export interface PlantillasResponse {
  data:          Plantilla[];
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface PlantillaResponse {
  data:          Plantilla;
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface Plantilla {
  idContratoTemplate: number;
  titulo:             string;
  template:           string;
  activo:             boolean;
}

export interface Hero {
  nombre:             string;
  descripcion:        string;
  valor:              string;
}

export const HEROES: Hero[] = [
  {nombre: 'nunum_empleado_rr_hh', descripcion: 'Número del empleado para control interno',valor: '80000' },
{nombre: 'nukidpersona', descripcion: 'Número de identificación de cada persona ',valor: '1944' },
{nombre: 'nombre_persona', descripcion: 'Nombre del Empleado para su contrato',valor: 'Gerardo Perez Carbajal' },
{nombre: 'dtfecha_nacimiento', descripcion: 'Fecha de necimiento del empleado',valor: '1983-01-24T00:00:00' },
{nombre: 'chedad', descripcion: 'Edad del Empleado',valor: '41 años' },
{nombre: 'nukidsexo', descripcion: 'Identificador del Sexo del Empleado 1,2,3',valor: '2' },
{nombre: 'chsexo', descripcion: 'Sexo del Empleado F/M/N',valor: 'M' },
{nombre: 'chcurp', descripcion: 'Curp del empleado',valor: 'LOAA890530MGRPVL06' },
{nombre: 'chrfc', descripcion: 'RFC del Empleado',valor: 'MORJ74082234' },
{nombre: 'chnacionalidad', descripcion: 'Nacionalidad del Empleado',valor: 'null' },
{nombre: 'nukidtipo_empleado', descripcion: 'Tipo del empleado',valor: '1' },
{nombre: 'chtipo_emplado', descripcion: 'Tipo empleado ',valor: 'contrato' },
{nombre: 'nukidcategoria', descripcion: 'Identificador de la categoria ',valor: '1' },
{nombre: 'chcategoria', descripcion: 'Categoria del empleado',valor: 'A' },
{nombre: 'nukidtipo_contrato', descripcion: 'Identificador del tipo de contrato que se asignara al empleado',valor: '1' },
{nombre: 'chtipo_contrato', descripcion: 'Tipo de contrato dependiedo el empleado',valor: 'T. Indeterminado' },
{nombre: 'chcve_puesto', descripcion: 'Nombre del puesto del empleado',valor: '1' },
{nombre: 'chpuesto', descripcion: 'Puesto del empleado',valor: 'Asistente Administrativo' },
{nombre: 'nukidempresa', descripcion: 'Identificador de la empresa',valor: '9' },
{nombre: 'chempresa', descripcion: 'Nombre de la empresa',valor: 'Bovis Project Management S.A. de C.V.' },
{nombre: 'chcalle', descripcion: 'Nombre de la calle ',valor: 'Ayate' },
{nombre: 'nunumero_interior', descripcion: 'Numero interior del domicilio',valor: '10' },
{nombre: 'nunumero_exterior', descripcion: 'Numero exterior del domicilio',valor: '260' },
{nombre: 'chcolonia', descripcion: 'Nombre de la colonia ',valor: 'centro' },
{nombre: 'chalcaldia', descripcion: 'Nombre de la alcaldia ',valor: 'bj' },
{nombre: 'nukidciudad', descripcion: 'Identificador del nombre de la ciudad ',valor: '12' },
{nombre: 'chciudad', descripcion: 'Nombre de la ciudad ',valor: 'Tecate' },
{nombre: 'nukidestado', descripcion: 'Identificador del estado ',valor: '36' },
{nombre: 'chestado', descripcion: 'Nombre del estado',valor: 'Baja California' },
{nombre: 'chcp', descripcion: 'Codigo postal del empleado',valor: '52227' },
{nombre: 'nukidpais', descripcion: 'Identificador del pais del empleado',valor: '1' },
{nombre: 'chpais', descripcion: 'Nombre del pais ',valor: 'MEX' },
{nombre: 'nukidnivel_estudios', descripcion: 'Identificador del nivel de estudios',valor: '1' },
{nombre: 'chnivel_estudios', descripcion: 'Nombre del nivel de estudios de cada empleado',valor: 'Bachillerato' },
{nombre: 'nukidforma_pago', descripcion: 'Forma de pago para el empleado',valor: '3' },
{nombre: 'chforma_pago', descripcion: 'Transferencia / Efectivo / Cheque',valor: 'Transferencia' },
{nombre: 'nukidjornada', descripcion: 'Identificador de la jornada del empleado',valor: '2' },
{nombre: 'chjornada', descripcion: 'Mixta / completa / Remoto',valor: 'Mixta' },
{nombre: 'nukiddepartamento', descripcion: 'Identificador de cada uno de los departamentos posibles',valor: '1' },
{nombre: 'chdepartamento', descripcion: 'Departamento al que pertenece el empleado',valor: 'departamento 1' },
{nombre: 'nukidclasificacion', descripcion: 'Identificacion de la clasificación del empleado',valor: '1' },
{nombre: 'chclasificacion', descripcion: 'Clasificacion del empleado ',valor: '1' },
{nombre: 'nukidjefe_directo', descripcion: 'Identificacion del jefe directo del empleado',valor: '1979' },
{nombre: 'chjefe_directo', descripcion: 'Nombre del jefe directo del empleado',valor: 'Edgar Alejandro Carabantes Perez' },
{nombre: 'nukidunidad_negocio', descripcion: 'identificador de la unidad de negocio',valor: '1' },
{nombre: 'chunidad_negocio', descripcion: 'Nombre de la identificacion de la unidad de negocio',valor: 'Edificación' },
{nombre: 'nukidtipo_contrato_sat', descripcion: 'Identificacion del contrato SAT',valor: '0' },
{nombre: 'chtipo_contrato_sat', descripcion: 'Tipo de contrato del SAT',valor: '1' },
{nombre: 'nunum_empleado', descripcion: 'Numero de empleado interno para su control',valor: '80000' },
{nombre: 'dtfecha_ingreso', descripcion: 'Fecha en la que ingreso el empleado 23/08/2024',valor: '23/08/2024' },
{nombre: 'dtfecha_salida', descripcion: 'Fecha de salida del empleado 13/09/2024',valor: '13/09/2024' },
{nombre: 'dtfecha_ultimo_reingreso', descripcion: 'Fecha del ultimo reingreso del empleado 17/09/2024',valor: '17/09/2024' },
{nombre: 'chnss', descripcion: 'Numero de seguridad social del empleado 2238996009',valor: '2238996009' },
{nombre: 'chemail_bovis', descripcion: 'Email del empleado corporativo gp.carbajal@hunkabann.com.mx',valor: 'gp.carbajal@hunkabann.com.mx' },
{nombre: 'salarioenLetras', descripcion: 'Salario en letras y numero del empleado',valor: '$16,920.50 DIECISEIS MIL NOVECIENTOS VEINTE CON 50/100 M.N.' },
{nombre: 'nukidprofesion', descripcion: 'identificador de profeción del empleado',valor: '15' },
{nombre: 'chprofesion', descripcion: 'Nombre de la profecion del empleado, Ing. Lic, etc. ',valor: 'Ing. en Comunicaciones y Electrónica' },
{nombre: 'nuantiguedad', descripcion: 'Que antigüedad tiene cada uno de los empleados - 0 años, 0 meses, -4 días',valor: '0 años, 0 meses, -4 días' },
{nombre: 'nukidturno', descripcion: 'Identificador del turno de los empleados',valor: 'null' },
{nombre: 'chturno', descripcion: 'Turno del empleado - Matitino - Verpertino - Nocturno',valor: '' },
{nombre: 'nuunidad_medica', descripcion: 'identificador de la unidad medica del empleado',valor: 'null' },
{nombre: 'chregistro_patronal', descripcion: 'Numero de registro patronal ',valor: '3454356457' },
{nombre: 'chcotizacion', descripcion: 'Cotizacion del costo para contratar un empleado',valor: '1600' },
{nombre: 'nuduracion', descripcion: 'Tiempo que estara el empleado ',valor: 'null' },
{nombre: 'boactivo', descripcion: 'Identificador para un empleado Activo o NO Activo',valor: 'true' },
{nombre: 'boempleado', descripcion: 'Activo / No Activo',valor: 'true' },
{nombre: 'chporcentaje_pension', descripcion: 'Descuento de la pension que se le retendra al empleado',valor: 'NA' },
{nombre: 'nudescuento_pension', descripcion: 'Descuento aplicado de pension ',valor: '0' },
{nombre: 'nuporcentaje_pension', descripcion: 'null',valor: 'null' },
{nombre: 'nufondo_fijo', descripcion: 'Fonde de ahorro fijo que se retendra al empleado',valor: 'null' },
{nombre: 'nucredito_infonavit', descripcion: 'Credito de infonavit del empleado',valor: 'null' },
{nombre: 'chtipo_descuento', descripcion: 'Descuento que se le aplicara al empleado ',valor: 'null' },
{nombre: 'nuvalor_descuento', descripcion: 'Cantidad del descuento al empleado',valor: 'null' },
{nombre: 'nuno_empleado_noi', descripcion: 'Numero Noi para control interno ',valor: 'null' },
{nombre: 'chrol', descripcion: 'Roll que desempeñara el empleado',valor: 'Tester' },
{nombre: 'dtvigencia', descripcion: 'Vigencia del contrato del empleado',valor: '22/09/2024' },
{nombre: 'dtvigencia90', descripcion: 'Videncia a 30/90 Días para el contrato del empleado',valor: '21/11/2024' },
{nombre: 'cantidadEnLetras', descripcion: 'Cantidad en letras del sueldo del empleado DIECISEIS MIL NOVECIENTOS VEINTE CON 50/100',valor: 'DIECISEIS MIL NOVECIENTOS VEINTE CON 50/100' },
{nombre: 'chexperiencias', descripcion: 'Experiencias que tiene el empleado ',valor: 'Centros Comerciales' },
{nombre: 'chhabilidades', descripcion: 'Habilidades que tiene el empleado',valor: 'Comunicación' },
{nombre: 'nuproyecto_principal', descripcion: 'Proyecto principal al que esta asignado el empleado',valor: '244' },
{nombre: 'chproyecto_principal', descripcion: 'Nombre del proyecto principal al que esta asignado ',valor: '111 Adecuaciones Piso 15' }
];

